### ISSUE TITLE
not written in rust

### ISSUE THREAD

**Issue by SEAPUNK** [AnthonySuper/hardwater#1]
the language of the gods

**Comment by AnthonySuper** [comment]
I chose not to use rust on this project for a few reasons:
1. Unfamiliarity. I don't know Rust nearly as well as I know C++.
2. Ease of use. If you look at the code, a lot of it would likely not translate well to Rust, since it's not _inherently safe_. It will require more discipline on my part to prevent a screwup, sure, but I have a near-suicidal degree of self-confidence.
3. Street Cred. Rust gets you hipster cred, but well-written, leak-free C++ gets you street cred with the greybeard UNIX guys, and those guys are the guys who are going to be looking at any applications I might send to grad schools.

**Comment by SEAPUNK** [comment]
wow give me a serious answer why don't you
